app/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('django.contrib.auth.urls')),
    path('avatar/<int:avatar_id>', views.avatar, name='avatar'),
    path('avatars/', views.avatars, name='avatars'),
    path('creator/<slug:creator_id>', views.creator, name='creator'),
    path('creators/', views.creators, name='creators'),
    path('item/<int:item_id>', views.item, name='item'),
    path('items/', views.items, name='items'),
    path('info/', views.info, name='info'),
    path('debug/', views.debug, name='debug'),
    path('userpage/<int:pk>', views.userpage, name='userpage'),
    path('folder/<int:pk>', views.folder, name='folder'),
    path('recommend/', views.recommend, name='recommend'),
    path('folders/', views.folders, name='folders'),
    path('all_folders/',views.all_folders,name='all_folders'),
    path('debug_folders/', views.debug_folders, name='debug_folders'),
    # path('please/', views.please, name='please'),
    path('api/avatar/', views.api_avatar, name='api_avatar'),
    path('api/item/', views.api_item, name='api_item'),
    path('secure_login/',views.secure_login, name='secure_login'),
]

kaogaii2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),  #追加
]

templates/all_folders.html
{% extends "base.html" %}
{% block content %}
    {% load humanize %}
    {% load static %}
    <h3 class="deco">All Folders List</h3>
    <form method="get" action="{% url 'app:all_folders' %}">
        {{ form }}
        <input type="submit" class="button" value="Filter" />
        （{{ total_folder_count|intcomma }} folders）
    </form>
    {% include 'page_object.html' with keyword='app:all_folders' %}
    {% for folder in folders %}
        <div class="creator">
            <a href="{% url 'app:folder' pk=folder.pk %}">{{ folder }}</a> by {{ folder.editor }}
        <ul>
            {% for avatar in folder.want_avatar.all %}
                <li>
                    <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                </li>
            {% endfor %}
            {% for item in folder.want_item.all %}
                <li>
                    <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                </li>
            {% endfor %}
            {% for avatar in folder.fav_avatar.all %}
                <li>
                    <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                </li>
            {% endfor %}
            {% for item in folder.fav_item.all %}
                <li>
                    <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}
{% include 'page_object.html' with keyword='app:all_folders' %}
{% endblock content %}

templates/base.html
{% load static %}
<html lang="ja">
    <head>
        <title>Avatar Network</title>
        <link rel="icon" href="{% static 'an_icon.png' %}" />
        <meta property="og:title" content="Avatar Network" />
        <meta property="og:description"
              content="BOOTHで販売されているアバターを、対応アイテムの数を元に検索できるサービスです。"/>
        <meta property="og:site_name" content="JapanBeatSaberLeague" />
        <meta property="og:url" content="{{ request.build_absolute_uri }}" />
        <meta property="og:image" content="{% static 'card.png' %}" />
        <meta name="twitter:card" content="{% static 'card.png' %}" />
        <meta name="twitter:site" content="@hibit_at" />
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}" />
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-JJ7VZ4RNWW"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-JJ7VZ4RNWW');
        </script>
    </head>
    <body>
        <id="pagetop" />
        <nav>
            <div class="navbar">
                <div class="inside-navbar">
                    <a href="{% url 'app:index' %}">Avatar Network</a>
                    /
                    <a href="{% url 'app:avatars' %}">Avatars</a>
                    /
                    <a href="{% url 'app:items' %}">Items</a>
                    /
                    <a href="{% url 'app:creators' %}">Creators</a>
                    /
                    <a href="{% url 'app:folders' %}">Folders</a>
                    /
                    <a href="{% url 'app:info' %}">Info</a>
                </div>
                <div class="inside-navbar" style="font-size:20px">
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle"
                                    type="button"
                                    id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true"
                                    aria-expanded="false"
                                    style="background-color:lightpink;border-style:none;font-size:20px;font-weight:bold">
                                <img src="{{ social.extra_data.profile_image_url_https }}" class="icon"/>
                                ようこそ、{{ user }} さん！
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                   href="{% url 'app:userpage' pk=user.pk %}">マイページ</a>
                                <hr>
                                {% for folder in user.customer.folder.all %}
                                    <a class="dropdown-item" href="{% url 'app:folder' pk=folder.pk %}">{{ folder }}</a>
                                {% endfor %}
                                <hr>
                                <a class="dropdown-item" href="{% url 'app:recommend' %}">追加提案</a>
                                <hr>
                                <a class="dropdown-item" href="{% url 'app:logout' %}">ログアウト</a>
                            </div>
                        </div>
                        {% else %}
                            <div class="dropdown" style="margin-right:200px">
                                <a href="{% url 'app:secure_login' %}" >ログイン</a>
                            </div>
                        {% endif %}
                </div>
            </div>
        </nav>
        <div class="content">
            {% block content %}
            {% endblock content %}
            <hr />
            <h3>
                <a href="{% url 'app:index' %}" class="deco">Top</a>
            </h3>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/creators.html
{% extends "base.html" %}
{% block content %}
    {% load humanize %}
    {% load static %}
    <h3 class="deco">Creators List</h3>
    <form method="get" action="{% url 'app:creators' %}">
        {{ form }}
        <input type="submit" class="button" value="Filter" />
        （{{ total|intcomma }} creators）
    </form>
    {% include 'page_object.html' with keyword='app:creators' %}
    {% for creator in creators %}
        {% if creator.highlight.all|length > 0 %}
            <div class="creator-highlight">
            {% else %}
                <div class="creator">
                {% endif %}
                <p style="display:inline">
                    <a href="{% url 'app:creator' creator_id=creator.creator_id %}">{{ creator }}</a>
                    {% if creator.highlight.all|length > 0 %}
                        <img src="{% static 'star.png' %}" width="15px" height="15px">
                    {% endif %}
                    <ul>
                        {% if creator.avatars.all|length > 0 %}
                            <li>Avatars</li>
                            <ul>
                                {% for avatar in creator.avatars.all %}
                                    <li>
                                        <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                                        {% if avatar.price > 0 %}
                                            <span class="price">¥ {{ avatar.price|intcomma }}</span>
                                        {% else %}
                                            <span class="free">¥ Free</span>
                                        {% endif %}
                                        {% if avatar.num_items > 0 %}
                                            対応アイテム
                                            <span class="price">{{ avatar.num_items|intcomma }}</span>
                                            点
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        {% if creator.items.all|length > 0 %}
                            <li>Items</li>
                            <ul>
                                {% for item in creator.items.all %}
                                    <li>
                                        <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                                        {% if item.price > 0 %}
                                            <span class="price">¥ {{ item.price|intcomma }}</span>
                                        {% else %}
                                            <span class="free">¥ Free</span>
                                        {% endif %}
                                        {% if item.num_avatars > 0 %}
                                            対応アバター
                                            <span class="price">{{ item.num_avatars|intcomma }}</span>
                                            体
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </ul>
                </p>
            </div>
        {% endfor %}
        {% include 'page_object.html' with keyword='app:creators' %}
    {% endblock content %}

templates/folders.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    {% load humanize %}
    <h3 class="deco">Folders List</h3>
    <a href="{% url 'app:all_folders' %}">
        <button class="button">All Folders</button>
    </a>
    <hr>
    {% for folder in folders %}
        <div class="creator">
            <p>
                <a href="{% url 'app:folder' pk=folder.pk %}"><b>{{ folder }}</b> by {{ folder.editor }}</a>
            </p>
            <p>
                {{ folder.description|truncatechars:30 }}
            </p>
            <div class="boxContainer">
                {% if folder.want_avatar.all|length > 0 %}
                    {% comment %} <div class="boxContainer"> {% endcomment %}
                    {% for avatar in folder.want_avatar.all|slice:":7" %}
                        <div class="box" style="width:160px;height:160px">
                            <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">
                                <img alt="thumb"
                                     src="{{ avatar.imageURL }}"
                                     class="thumb"
                                     {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                            </a>
                        </div>
                    {% endfor %}
                    {% comment %} </div> {% endcomment %}
                {% endif %}
                {% if folder.want_item.all|length > 0 %}
                    {% comment %} <div class="boxContainer"> {% endcomment %}
                    {% for item in folder.want_item.all|slice:":7" %}
                        <div class="box" style="width:160px;height:160px">
                            <a href="{% url 'app:item' item_id=item.item_id %}">
                                <img alt="thumb"
                                     src="{{ item.imageURL }}"
                                     class="thumb"
                                     {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                            </a>
                        </div>
                    {% endfor %}
                    {% comment %} </div> {% endcomment %}
                {% endif %}
                {% if folder.fav_avatar.all|length > 0 %}
                    {% comment %} <div class="boxContainer"> {% endcomment %}
                    {% for avatar in folder.fav_avatar.all|slice:":7" %}
                        <div class="box" style="width:160px;height:160px">
                            <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">
                                <img alt="thumb"
                                     src="{{ avatar.imageURL }}"
                                     class="thumb"
                                     {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                            </a>
                        </div>
                    {% endfor %}
                    {% comment %} </div> {% endcomment %}
                {% endif %}
                {% if folder.fav_item.all|length > 0 %}
                    {% comment %} <div class="boxContainer"> {% endcomment %}
                    {% for item in folder.fav_item.all|slice:":7" %}
                        <div class="box" style="width:160px;height:160px">
                            <a href="{% url 'app:item' item_id=item.item_id %}">
                                <img alt="thumb"
                                     src="{{ item.imageURL }}"
                                     class="thumb"
                                     {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                            </a>
                        </div>
                    {% endfor %}
                    {% comment %} </div> {% endcomment %}
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    {% load humanize %}
    <div class="welcome">
        <div>
            <h4 class="deco">！Discord 認証の追加について！</h4>
            <p>Discord による認証機能を実装しました。詳しくは<a href="{% url 'app:info' %}" class="bg_link">こちら</a>をご覧ください。</p>
        </div>
        <p class="deco">
            Welcome to Avatar Network
        </p>
        <p>
            <a href="{% url 'app:avatars' %}">アバター一覧から探す</a>
        </p>
        <p>
            <a href="{% url 'app:items' %}">アイテム一覧から探す</a>
        </p>
        <p>
            <a href="{% url 'app:creators' %}">クリエイター一覧から探す</a>
        </p>
        <p>
            <a href="{% url 'app:folders' %}">公開フォルダー一覧から探す</a>
        </p>
    </div>
    <hr />
    <h3 class="deco">Lucky Avatars</h3>
    <div class="boxContainer">
        {% for avatar in avatars %}
            <div class="box">
                <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">
                    <img src="{{ avatar.imageURL }}" class="thumb" alt="thumb" />
                </a>
                <p>
                    <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar|truncatechars:30 }}</a>
                    by
                    <a href="{% url 'app:creator' creator_id=avatar.creator.creator_id %}">{{ avatar.creator|truncatechars:20 }}</a>
                    <br />
                    {% include 'price_object.html' with price=avatar.price %}
                    <a href="https://booth.pm/ja/items/{{ avatar.avatar_id }}"
                       target="blank">
                        <img src="{% static 'BOOTH_emoji.png' %}" class="emoji" alt="emoji" />
                    </a>
                </p>
            </div>
        {% endfor %}
    </div>
    <hr />
    <h3 class="deco">Lucky Items</h3>
    <div class="boxContainer">
        {% for item in items %}
            <div class="box">
                <a href="{% url 'app:item' item_id=item.item_id %}">
                    <img src="{{ item.imageURL }}" class="thumb" alt="thumb"/>
                </a>
                <p>
                    <a href="{% url 'app:item' item_id=item.item_id %}">{{ item|truncatechars:30 }}</a>
                    by
                    <a href="{% url 'app:creator' creator_id=item.creator.creator_id %}">{{ item.creator|truncatechars:30 }}</a>
                    <br />
                    {% include 'price_object.html' with price=item.price %}
                    <a href="https://booth.pm/ja/items/{{ item.item_id }}" target="blank">
                        <img src="{% static 'BOOTH_emoji.png' %}" class="emoji" alt="emoji" />
                    </a>
                </p>
            </div>
        {% endfor %}
    </div>
    <hr />
    <h3 class="deco">Lucky Folder</h3>
    <div class="creator">
        <p>
            <a href="{% url 'app:folder' pk=folder.pk %}"><b>{{ folder }}</b> by {{ folder.editor }}</a>
        </p>
        <p>
            {{ folder.description|truncatechars:30 }}
        </p>
        <div class="boxContainer">
            {% if folder.want_avatar.all|length > 0 %}
                {% comment %} <div class="boxContainer"> {% endcomment %}
                {% for avatar in folder.want_avatar.all|slice:":3" %}
                    <div class="box" style="width:160px;height:160px">
                        <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">
                            <img alt="thumb"
                                 src="{{ avatar.imageURL }}"
                                 class="thumb"
                                 {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                        </a>
                    </div>
                {% endfor %}
                {% comment %} </div> {% endcomment %}
            {% endif %}
            {% if folder.want_item.all|length > 0 %}
                {% comment %} <div class="boxContainer"> {% endcomment %}
                {% for item in folder.want_item.all|slice:":3" %}
                    <div class="box" style="width:160px;height:160px">
                        <a href="{% url 'app:item' item_id=item.item_id %}">
                            <img alt="thumb"
                                 src="{{ item.imageURL }}"
                                 class="thumb"
                                 {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                        </a>
                    </div>
                {% endfor %}
                {% comment %} </div> {% endcomment %}
            {% endif %}
            {% if folder.fav_avatar.all|length > 0 %}
                {% comment %} <div class="boxContainer"> {% endcomment %}
                {% for avatar in folder.fav_avatar.all|slice:":3" %}
                    <div class="box" style="width:160px;height:160px">
                        <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">
                            <img alt="thumb"
                                 src="{{ avatar.imageURL }}"
                                 class="thumb"
                                 {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                        </a>
                    </div>
                {% endfor %}
                {% comment %} </div> {% endcomment %}
            {% endif %}
            {% if folder.fav_item.all|length > 0 %}
                {% comment %} <div class="boxContainer"> {% endcomment %}
                {% for item in folder.fav_item.all|slice:":3" %}
                    <div class="box" style="width:160px;height:160px">
                        <a href="{% url 'app:item' item_id=item.item_id %}">
                            <img alt="thumb"
                                 src="{{ item.imageURL }}"
                                 class="thumb"
                                 {% if folder.isNSFW %} style="width:150px;height:150px;filter:blur(10px)" {% else %} style="width:150px;height:150px" {% endif %}/>
                        </a>
                    </div>
                {% endfor %}
                {% comment %} </div> {% endcomment %}
            {% endif %}
        </div>
    </div>
    <hr />
    <h3 class="deco">Weekly Hot</h3>
    <ul>
        {% for avatar in hot_avatars %}
            <li>
                <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                {% include 'price_object.html' with price=avatar.price %}
                by
                <a href="{% url 'app:creator' creator_id=avatar.creator.creator_id %}">{{ avatar.creator }}</a>
                <span class="free">(+{{ avatar.item_hot }})</span>
            </li>
        {% endfor %}
        <a href="{% url 'app:avatars' %}?sort_hot=on">
            <button class="button">
                More Results
            </button>
        </a>
    </ul>
    <hr />
    <h3 class="deco">Most Wanted</h3>
    <ul>
        Avatars
        <ul>
            {% for avatar in wanted_avatars %}
                <li>
                    <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                    {% include 'price_object.html' with price=avatar.price %}
                    by
                    <a href="{% url 'app:creator' creator_id=avatar.creator.creator_id %}">{{ avatar.creator }}</a>
                    <span class="free">({{ avatar.want }} wanted)</span>
                </li>
            {% endfor %}
        </ul>
        Items
        <ul>
            {% for item in wanted_items %}
                <li>
                    <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                    {% include 'price_object.html' with price=item.price %}
                    by
                    <a href="{% url 'app:creator' creator_id=item.creator.creator_id %}">{{ item.creator }}</a>
                    <span class="free">({{ item.want }} wanted)</span>
                </li>
            {% endfor %}
        </ul>
    </ul>
    <hr />
    <h3 class="deco">Recent Updates</h3>
    <ul>
        Avatars
        <ul>
            {% for avatar in recent_avatars %}
                <li>
                    <a href="{% url 'app:avatar' avatar_id=avatar.avatar_id %}">{{ avatar }}</a>
                    {% include 'price_object.html' with price=avatar.price %}
                    by
                    <a href="{% url 'app:creator' creator_id=avatar.creator.creator_id %}">{{ avatar.creator }}</a>
                </li>
            {% endfor %}
        </ul>
        Items
        <ul>
            {% for item in recent_items %}
                <li>
                    <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                    {% include 'price_object.html' with price=item.price %}
                    by
                    <a href="{% url 'app:creator' creator_id=item.creator.creator_id %}">{{ item.creator }}</a>
                </li>
            {% endfor %}
        </ul>
    </ul>
    <hr />
    <h4 class="deco">
        Supporters
    </h4>
    <p>
        以下の方々にご支援いただいています。ありがとうございます。
    </p>
    <ul>
        {% for supporter in supporters %}
            <li>
                {{ supporter }} 様
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/items.html
{% extends "base.html" %}
{% block content %}
    {% load humanize %}
    {% load static %}
    <script src="{% static 'folder_form.js' %}"></script>
    <h3 class="deco">Items List</h3>
    <form method="get" action="{% url 'app:items' %}">
        {{ form }}
        {% if sort_latest %}<input type="hidden" name="sort_latest" value="on" />{% endif %}
        <input type="submit" value="Filter" class="button" />
        （{{ total|intcomma }} items）
        {% if sort_latest %}
            Sort by Latest
            <button name="sort_latest" value="off" class="button">to Total</button>
        {% else %}
            Sort by Total
            <button name="sort_latest" value="on" class="button">to Latest</button>
        {% endif %}
    </form>
    {% include 'page_object.html' with keyword='app:items' add_bool=sort_latest add_str='sort_latest' %}
    {% for item in items %}
        {% if item.isHighlight %}
            <div class="boxrow-highlight">
            {% else %}
                <div class="boxrow">
                {% endif %}
                <div style="width:200px">
                    <a href="{% url 'app:item' item_id=item.item_id %}">
                        <img src="{{ item.imageURL }}" class="thumb" alt="thumb" />
                    </a>
                </div>
                <div style="width:auto;margin-left:20px">
                    <p>
                        <a href="{% url 'app:item' item_id=item.item_id %}">{{ item }}</a>
                    </p>
                    <p>
                        by
                        <a href="{% url 'app:creator' creator_id=item.creator.creator_id %}">{{ item.creator }}</a>
                    </p>
                対応アバター：<span class="price">{{ item.avatar.all|length }}</span> 点
                <p>
                    {% include 'price_object.html' with price=item.price %}
                    <a href="https://booth.pm/ja/items/{{ item.item_id }}" target="blank">
                        <img src="{% static 'BOOTH_emoji.png' %}" class="emoji" alt="emoji" />
                    </a>
                </p>
                {% if user.is_authenticated %}
                    <div class="folder_button_container btn-group dropright">
                        <button type="button"
                                class="folder_button btn btn-secondary dropdown-toggle {% if item.folders_wanted %}button_already{% else %}button{% endif %}"
                                data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false">
                        {% if item.folders_wanted %}
                            ✔ WANT
                        {% else %}
                            +WANT
                        {% endif %}
                    </button>
                    <div class="dropdown-menu">
                        <!-- Dropdown menu links -->
                        {% for folder in folders %}
                            <a class="dropdown-item"
                               href="{% url 'app:folder' pk=folder.pk %}"
                               style="display:inline;line-height:40px">
                                {% if folder not in item.folders_wanted %}
                                    <form class="folder_form"
                                          method="post"
                                          style="display:inline"
                                          action="{% url 'app:item' item_id=item.item_id %}">
                                        {% csrf_token %}
                                        <button class="button" name="add_want" value="{{ folder.pk }}">+WANT</button>
                                    </form>
                                {% else %}
                                    <button class="button_already" disabled>Added</button>
                                {% endif %}
                                {{ folder }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
                <div class="folder_button_container btn-group dropright">
                    <button type="button"
                            class="folder_button btn btn-secondary dropdown-toggle {% if item.folders_owned %}button_already{% else %}button{% endif %}"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                            >
                    {% if item.folders_owned %}
                        ✔ OWNED
                    {% else %}
                        +OWNED
                    {% endif %}
                </button>
                <div class="dropdown-menu">
                    <!-- Dropdown menu links -->
                    {% for folder in folders %}
                        <a class="dropdown-item"
                           href="{% url 'app:folder' pk=folder.pk %}"
                           style="display:inline;line-height:40px">
                            {% if folder not in item.folders_owned %}
                                <form class="folder_form"
                                      method="post"
                                      style="display:inline"
                                      action="{% url 'app:item' item_id=item.item_id %}">
                                    {% csrf_token %}
                                    <button class="button" name="add" value="{{ folder.pk }}">+OWNED</button>
                                </form>
                            {% else %}
                                <button class="button_already" disabled>Added</button>
                            {% endif %}
                            {{ folder }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endfor %}
{% include 'page_object.html' with keyword='app:items' add_bool=sort_latest add_str='sort_latest' %}
{% endblock content %}

templates/price_object.html
{% load humanize %}
{% if price > 0 %}
    <span class="price">¥ {{ price|intcomma }}</span>
{% else %}
    <span class="free">¥ Free</span>
{% endif %}

templates/suspend.html
本サービスは公開停止中です。
申し訳ありません。